#Generated Form Function
function GenerateForm {
########################################################################
# Mailbox Cross Forest Mover by Ralf Bönisch (Skyborg)
# Generated On: 13.02.2012 23:30
# Generated By: Skyborg (Ralf Bönisch)
# Version 0.61 Add: Zugriff aus der Quelldomäne
# Release History:
# Version 0.5 Add: Mailbox-Statistics-Button
# Version 0.4 Add Option for Mailnickname
# Version 0.3 output on powershell screen
# Version 0.2 Failure detection
# Version 0.1 Main Functions
########################################################################

#region Globals - Hier die Variablen eintragen
##RemoteForestDomainController - FQDN
$RFDC="dc01.source.net"
##LocalForestDomainController - FQDN
$LFDC="dc02.destination.net"
##TargetDatabase
$TargetDB="Mailbox Database 01"
##RemoteGlobalCatalog  - FQDN
$RGC="dc01.source.net"
##TargetDeliveryDomain  - FQDN domain.ads
$TFQDN="destiantion.net"
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$groupBox2 = New-Object System.Windows.Forms.GroupBox
$button_perm_source = New-Object System.Windows.Forms.Button
$button_moveoverview = New-Object System.Windows.Forms.Button
$button_csv = New-Object System.Windows.Forms.Button
$button_mailmove = New-Object System.Windows.Forms.Button
$button_mailprep = New-Object System.Windows.Forms.Button
$button_mailac = New-Object System.Windows.Forms.Button
$groupBox1 = New-Object System.Windows.Forms.GroupBox
$button_zielb = New-Object System.Windows.Forms.Button
$button_quellb = New-Object System.Windows.Forms.Button
$label1 = New-Object System.Windows.Forms.Label
$textBox_quelle = New-Object System.Windows.Forms.TextBox
$button_quelle = New-Object System.Windows.Forms.Button
$openFileDialog1 = New-Object System.Windows.Forms.OpenFileDialog
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$button_quelle_OnClick= 
{
  $result = $openfiledialog1.ShowDialog()
   if ($result -eq 'Ok'){
       $textBox_quelle.Text = $openfiledialog1.FileName
   }else{
      $textBox_quelle.Text = ''
  }

}

$button_perm_source_OnClick= 
{
write-host "Benutzer wird Mail-Aktiviert" -BackgroundColor Blue
 if ($textBox_quelle.Text -eq '' -or $(!$RemoteCredentials) -or $(!$LocalCredentials)){
     if ($textBox_quelle.Text -eq '') {write-warning "Bitte CSV-Datei auswählen"}  
	 if (!$RemoteCredentials) {write-warning "Bitte Quell-Benutzer festlegen"}
	 if (!$LocalCredentials) {write-warning "Bitte Ziel-Benutzer festlegen"}
   }else{
      write-host "Schritt 1: Mailbox Zugriff" -BackgroundColor Blue
	  import-csv $textBox_quelle.Text | ForEach-Object -process {
		$SrcUsr=$_.sAMAccountName
		write-host "Benutzer: $SrcUsr" -BackgroundColor Blue
		Get-MailboxPermission $_.sAMAccountName | Add-MailboxPermission -User "source.net\$SrcUsr" -AccessRights FullAccess | out-host
		}
	  write-host "Schritt 1: Ende" -BackgroundColor Blue
	  write-host "Schritt 2: SendAs-Rechte" -BackgroundColor Blue
	  import-csv $textBox_quelle.Text | ForEach-Object -process {
		$SrcUsr=$_.sAMAccountName
		write-host "Benutzer: $SrcUsr" -BackgroundColor Blue
		Add-ADPermission -Identity $_.displayName -User "source.net\$SrcUsr" -ExtendedRights "Send As" | out-host
	  }
	  write-host "Schritt 2: Ende" -BackgroundColor Blue
	  write-host "...erledigt" -BackgroundColor Blue
   }

}

$button_quellb_OnClick= 
{
$RemoteCredentials = get-credential

}

$button_mailac_OnClick= 
{
write-host "Benutzer wird Mail-Aktiviert" -BackgroundColor Blue
 if ($textBox_quelle.Text -eq '' -or $(!$RemoteCredentials) -or $(!$LocalCredentials)){
     if ($textBox_quelle.Text -eq '') {write-warning "Bitte CSV-Datei auswählen"}  
	 if (!$RemoteCredentials) {write-warning "Bitte Quell-Benutzer festlegen"}
	 if (!$LocalCredentials) {write-warning "Bitte Ziel-Benutzer festlegen"}
   }else{
	  import-csv $textBox_quelle.Text | ForEach-Object -process {Enable-MailUser -identity $_.sAMAccountName -ExternalEmailAddress $_.mail} | out-host
	  write-host "...erledigt" -BackgroundColor Blue
   }
}

$button_moveoverview_OnClick= 
{
write-host "Liste der offenen Move-Jobs:" -BackgroundColor Blue
Get-MoveRequest | where {$_.Status -ne "Completed"} | out-host
write-host "...erledigt" -BackgroundColor Blue
}

$button_zielb_OnClick= 
{
$LocalCredentials = get-credential

}

$handler_label1_Click= 
{
#TODO: Place custom script here

}

$button_mailprep_OnClick= 
{
write-host "Benutzer wird mit für den Move vorbereitet" -BackgroundColor Blue
 if ($textBox_quelle.Text -eq '' -or $(!$RemoteCredentials) -or $(!$LocalCredentials)){
     if ($textBox_quelle.Text -eq '') {write-warning "Bitte CSV-Datei auswählen"}  
	 if (!$RemoteCredentials) {write-warning "Bitte Quell-Benutzer festlegen"}
	 if (!$LocalCredentials) {write-warning "Bitte Ziel-Benutzer festlegen"}
   }else{
      import-csv $textBox_quelle.Text | ForEach-Object –process {./Prepare-MoveRequest.ps1 -identity $_.mailNickname  -RemoteForestDomainController $RFDC -RemoteForestCredential $RemoteCredentials -LocalForestDomainController $LFDC -LocalForestCredential $LocalCredentials -UseLocalObject} | out-host
      write-host "...erledigt" -BackgroundColor Blue
  }


}

$button_csv_OnClick= 
{
if ($textBox_quelle.Text -eq ''){ 
	write-warning "Bitte CSV-Datei auswählen"
   }else{
      write-host "Liste wird erstellt... :" -BackgroundColor Blue
	  write-host "SAM-Name: , E-Mail: , MailNickname: "
	  import-csv $textBox_quelle.Text | ForEach-Object –process {write-host $_.sAMAccountName " , " $_.mail " , " $_.mailNickname} | out-host
	  write-host "...erledigt" -BackgroundColor Blue
   }

}

$button_mailmove_OnClick= 
{
write-host "Benutzer wird auf den neuen Exchange verschoben" -BackgroundColor Blue
 if ($textBox_quelle.Text -eq '' -or $(!$RemoteCredentials) -or $(!$LocalCredentials)){
     if ($textBox_quelle.Text -eq '') {write-warning "Bitte CSV-Datei auswählen"}  
	 if (!$RemoteCredentials) {write-warning "Bitte Quell-Benutzer festlegen"}
	 if (!$LocalCredentials) {write-warning "Bitte Ziel-Benutzer festlegen"}
   }else{
	  import-csv $textBox_quelle.Text | ForEach-Object –process {new-moverequest -identity $_.sAMAccountName -RemoteLegacy -TargetDatabase $TargetDB -RemoteGlobalCatalog $RGC -RemoteCredential $RemoteCredentials -TargetDeliveryDomain $TFQDN} | out-host
      write-host "...erledigt" -BackgroundColor Blue
   }
}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 270
$System_Drawing_Size.Width = 588
$form1.ClientSize = $System_Drawing_Size
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$form1.Name = "form1"
$form1.Text = "Mailbox Cross Forest Mover von Ralf Bönisch"


$groupBox2.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 404
$System_Drawing_Point.Y = 90
$groupBox2.Location = $System_Drawing_Point
$groupBox2.Name = "groupBox2"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 71
$System_Drawing_Size.Width = 159
$groupBox2.Size = $System_Drawing_Size
$groupBox2.TabIndex = 10
$groupBox2.TabStop = $False
$groupBox2.Text = "Zugriff von der Quelle"

$form1.Controls.Add($groupBox2)

$button_perm_source.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 6
$System_Drawing_Point.Y = 29
$button_perm_source.Location = $System_Drawing_Point
$button_perm_source.Name = "button_perm_source"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 136
$button_perm_source.Size = $System_Drawing_Size
$button_perm_source.TabIndex = 0
$button_perm_source.Text = "Zugriff für Quellbenutzer"
$button_perm_source.UseVisualStyleBackColor = $True
$button_perm_source.add_Click($button_perm_source_OnClick)

$groupBox2.Controls.Add($button_perm_source)



$button_moveoverview.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 465
$System_Drawing_Point.Y = 222
$button_moveoverview.Location = $System_Drawing_Point
$button_moveoverview.Name = "button_moveoverview"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 98
$button_moveoverview.Size = $System_Drawing_Size
$button_moveoverview.TabIndex = 9
$button_moveoverview.Text = "Move Übersicht"
$button_moveoverview.UseVisualStyleBackColor = $True
$button_moveoverview.add_Click($button_moveoverview_OnClick)

$form1.Controls.Add($button_moveoverview)


$button_csv.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 465
$System_Drawing_Point.Y = 35
$button_csv.Location = $System_Drawing_Point
$button_csv.Name = "button_csv"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$button_csv.Size = $System_Drawing_Size
$button_csv.TabIndex = 8
$button_csv.Text = "Zeige Inhalt"
$button_csv.UseVisualStyleBackColor = $True
$button_csv.add_Click($button_csv_OnClick)

$form1.Controls.Add($button_csv)


$button_mailmove.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 220
$System_Drawing_Point.Y = 177
$button_mailmove.Location = $System_Drawing_Point
$button_mailmove.Name = "button_mailmove"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 143
$button_mailmove.Size = $System_Drawing_Size
$button_mailmove.TabIndex = 7
$button_mailmove.Text = "3. Mailbox verschieben"
$button_mailmove.UseVisualStyleBackColor = $True
$button_mailmove.add_Click($button_mailmove_OnClick)

$form1.Controls.Add($button_mailmove)


$button_mailprep.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 220
$System_Drawing_Point.Y = 138
$button_mailprep.Location = $System_Drawing_Point
$button_mailprep.Name = "button_mailprep"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 143
$button_mailprep.Size = $System_Drawing_Size
$button_mailprep.TabIndex = 6
$button_mailprep.Text = "2. Verschieben vorbereiten"
$button_mailprep.UseVisualStyleBackColor = $True
$button_mailprep.add_Click($button_mailprep_OnClick)

$form1.Controls.Add($button_mailprep)


$button_mailac.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 220
$System_Drawing_Point.Y = 98
$button_mailac.Location = $System_Drawing_Point
$button_mailac.Name = "button_mailac"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 143
$button_mailac.Size = $System_Drawing_Size
$button_mailac.TabIndex = 5
$button_mailac.Text = "1. E-Mail-Aktivierung"
$button_mailac.UseVisualStyleBackColor = $True
$button_mailac.add_Click($button_mailac_OnClick)

$form1.Controls.Add($button_mailac)


$groupBox1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 31
$System_Drawing_Point.Y = 90
$groupBox1.Location = $System_Drawing_Point
$groupBox1.Name = "groupBox1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 118
$System_Drawing_Size.Width = 137
$groupBox1.Size = $System_Drawing_Size
$groupBox1.TabIndex = 4
$groupBox1.TabStop = $False
$groupBox1.Text = "Authentifizierung"

$form1.Controls.Add($groupBox1)

$button_zielb.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 17
$System_Drawing_Point.Y = 68
$button_zielb.Location = $System_Drawing_Point
$button_zielb.Name = "button_zielb"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 98
$button_zielb.Size = $System_Drawing_Size
$button_zielb.TabIndex = 4
$button_zielb.Text = "Ziel-Benutzer"
$button_zielb.UseVisualStyleBackColor = $True
$button_zielb.add_Click($button_zielb_OnClick)

$groupBox1.Controls.Add($button_zielb)


$button_quellb.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 17
$System_Drawing_Point.Y = 29
$button_quellb.Location = $System_Drawing_Point
$button_quellb.Name = "button_quellb"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 98
$button_quellb.Size = $System_Drawing_Size
$button_quellb.TabIndex = 3
$button_quellb.Text = "Quell-Benutzer"
$button_quellb.UseVisualStyleBackColor = $True
$button_quellb.add_Click($button_quellb_OnClick)

$groupBox1.Controls.Add($button_quellb)


$label1.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 31
$System_Drawing_Point.Y = 21
$label1.Location = $System_Drawing_Point
$label1.Name = "label1"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 13
$System_Drawing_Size.Width = 100
$label1.Size = $System_Drawing_Size
$label1.TabIndex = 2
$label1.Text = "Quelle: CSV-Datei"
$label1.add_Click($handler_label1_Click)

$form1.Controls.Add($label1)

$textBox_quelle.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 31
$System_Drawing_Point.Y = 37
$textBox_quelle.Location = $System_Drawing_Point
$textBox_quelle.Name = "textBox_quelle"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 20
$System_Drawing_Size.Width = 285
$textBox_quelle.Size = $System_Drawing_Size
$textBox_quelle.TabIndex = 1

$form1.Controls.Add($textBox_quelle)


$button_quelle.DataBindings.DefaultDataSourceUpdateMode = 0

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 343
$System_Drawing_Point.Y = 35
$button_quelle.Location = $System_Drawing_Point
$button_quelle.Name = "button_quelle"
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 102
$button_quelle.Size = $System_Drawing_Size
$button_quelle.TabIndex = 0
$button_quelle.Text = "Quelle wählen"
$button_quelle.UseVisualStyleBackColor = $True
$button_quelle.add_Click($button_quelle_OnClick)

$form1.Controls.Add($button_quelle)

$openFileDialog1.FileName = "openFileQuelle"
$openFileDialog1.Filter = "CSV-Dateien|*.csv"
$openFileDialog1.InitialDirectory = "C:\temp"
$openFileDialog1.ShowHelp = $True

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
